ALTER SERVER ROLE [sysadmin] ADD MEMBER [LAPTOP-OUKIIKJ4\MoZapT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

