USE [master]
GO

/****** Object:  Database [FCC]    Script Date: 23.10.2019 15:00:23 ******/
CREATE DATABASE [FCC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FCC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FCC.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FCC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FCC_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FCC] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FCC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FCC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FCC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FCC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FCC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FCC] SET ARITHABORT OFF 
GO

ALTER DATABASE [FCC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FCC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FCC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FCC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FCC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FCC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FCC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FCC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FCC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FCC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FCC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FCC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FCC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FCC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FCC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FCC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FCC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FCC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FCC] SET  MULTI_USER 
GO

ALTER DATABASE [FCC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FCC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FCC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FCC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FCC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FCC] SET  READ_WRITE 
GO


